services:
  - type: web
    name: hackhub
    env: docker
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 8085
    disk:
      name: hackhub-uploads
      mountPath: /app/uploads
      sizeGB: 1
